# Simulator Configuration

# Starting balance
initial_balance: 10000.0

# Position sizing: how much percentage of our capital is invested in a single trade
position_size:
  type: fixed_percentage
  value: 10.0

# Fees & Slippage
# 0.05% fee per trade taken by the broker
commission: 0.0005
# 0.02% expected price slippage
slippage: 0.0002

# Trade Rules
allow_long: true
allow_short: true
