symbol: BTC
timeframe: 15m
features_count: 13
train_rows: 36589
val_rows: 7841
test_rows: 7841
leaderboard:
- model: xgboost
  hyperparameters:
    n_estimators: 100
    max_depth: 5
  model_file: D:\Neurog_Internship\cryptosight\ml\artifacts\models\BTC_15m_xgboost.joblib
  prediction_file: D:\Neurog_Internship\cryptosight\ml\csv_files\classification\model_predicted\BTC_xgboost_predicted.csv
  train_accuracy: 70.77%
  train_correct: 25893
  train_total: 36589
  train_loss: 0.7848
  val_accuracy: 32.88%
  val_precision: 63.06%
  val_recall: 32.88%
  val_correct: 2578
  val_total: 7841
  val_loss: 1.2856
  test_accuracy: 36.13%
  test_correct: 2833
  test_total: 7841
  test_loss: 1.2328
- model: lightgbm
  hyperparameters:
    class_weight: balanced
    n_estimators: 100
    learning_rate: 0.05
    verbosity: -1
  model_file: D:\Neurog_Internship\cryptosight\ml\artifacts\models\BTC_15m_lightgbm.joblib
  prediction_file: D:\Neurog_Internship\cryptosight\ml\csv_files\classification\model_predicted\BTC_lightgbm_predicted.csv
  train_accuracy: 65.23%
  train_correct: 23868
  train_total: 36589
  train_loss: 0.8916
  val_accuracy: 32.22%
  val_precision: 65.57%
  val_recall: 32.22%
  val_correct: 2526
  val_total: 7841
  val_loss: 1.2856
  test_accuracy: 33.47%
  test_correct: 2624
  test_total: 7841
  test_loss: 1.2514
- model: random_forest
  hyperparameters:
    class_weight: balanced
    n_estimators: 100
    max_depth: 5
  model_file: D:\Neurog_Internship\cryptosight\ml\artifacts\models\BTC_15m_random_forest.joblib
  prediction_file: D:\Neurog_Internship\cryptosight\ml\csv_files\classification\model_predicted\BTC_random_forest_predicted.csv
  train_accuracy: 59.73%
  train_correct: 21853
  train_total: 36589
  train_loss: 0.9657
  val_accuracy: 27.14%
  val_precision: 67.06%
  val_recall: 27.14%
  val_correct: 2128
  val_total: 7841
  val_loss: 1.319
  test_accuracy: 22.15%
  test_correct: 1737
  test_total: 7841
  test_loss: 1.3314
