symbol: BTC
timeframe: 15m
features_count: 13
train_rows: 36589
val_rows: 7841
test_rows: 7841
leaderboard:
- model: svm
  train_accuracy: 70.08%
  train_correct: 25640
  train_total: 36589
  train_loss: 0.6716
  val_accuracy: 55.29%
  val_precision: 58.28%
  val_recall: 55.29%
  val_correct: 4335
  val_total: 7841
  val_loss: 0.8256
  test_accuracy: 66.36%
  test_correct: 5203
  test_total: 7841
  test_loss: 0.6657
  model_file: D:\Neurog_Internship\cryptosight\ml\artifacts\models\BTC_15m_svm.joblib
  prediction_file: D:\Neurog_Internship\cryptosight\ml\csv_files\classification\model_predicted\BTC_svm_predicted.csv
- model: logistic_regression
  train_accuracy: 66.00%
  train_correct: 24148
  train_total: 36589
  train_loss: 0.9982
  val_accuracy: 43.95%
  val_precision: 61.43%
  val_recall: 43.95%
  val_correct: 3446
  val_total: 7841
  val_loss: 1.1588
  test_accuracy: 53.30%
  test_correct: 4179
  test_total: 7841
  test_loss: 1.1112
  model_file: D:\Neurog_Internship\cryptosight\ml\artifacts\models\BTC_15m_logistic_regression.joblib
  prediction_file: D:\Neurog_Internship\cryptosight\ml\csv_files\classification\model_predicted\BTC_logistic_regression_predicted.csv
- model: xgboost
  train_accuracy: 70.77%
  train_correct: 25893
  train_total: 36589
  train_loss: 0.7848
  val_accuracy: 32.88%
  val_precision: 63.06%
  val_recall: 32.88%
  val_correct: 2578
  val_total: 7841
  val_loss: 1.2856
  test_accuracy: 36.13%
  test_correct: 2833
  test_total: 7841
  test_loss: 1.2328
  model_file: D:\Neurog_Internship\cryptosight\ml\artifacts\models\BTC_15m_xgboost.joblib
  prediction_file: D:\Neurog_Internship\cryptosight\ml\csv_files\classification\model_predicted\BTC_xgboost_predicted.csv
- model: lightgbm
  train_accuracy: 65.23%
  train_correct: 23868
  train_total: 36589
  train_loss: 0.8916
  val_accuracy: 32.22%
  val_precision: 65.57%
  val_recall: 32.22%
  val_correct: 2526
  val_total: 7841
  val_loss: 1.2856
  test_accuracy: 33.47%
  test_correct: 2624
  test_total: 7841
  test_loss: 1.2514
  model_file: D:\Neurog_Internship\cryptosight\ml\artifacts\models\BTC_15m_lightgbm.joblib
  prediction_file: D:\Neurog_Internship\cryptosight\ml\csv_files\classification\model_predicted\BTC_lightgbm_predicted.csv
- model: decision_tree
  train_accuracy: 57.32%
  train_correct: 20974
  train_total: 36589
  train_loss: 0.9654
  val_accuracy: 31.83%
  val_precision: 64.79%
  val_recall: 31.83%
  val_correct: 2496
  val_total: 7841
  val_loss: 1.2984
  test_accuracy: 33.18%
  test_correct: 2602
  test_total: 7841
  test_loss: 1.2661
  model_file: D:\Neurog_Internship\cryptosight\ml\artifacts\models\BTC_15m_decision_tree.joblib
  prediction_file: D:\Neurog_Internship\cryptosight\ml\csv_files\classification\model_predicted\BTC_decision_tree_predicted.csv
- model: random_forest
  train_accuracy: 59.73%
  train_correct: 21853
  train_total: 36589
  train_loss: 0.9657
  val_accuracy: 27.14%
  val_precision: 67.06%
  val_recall: 27.14%
  val_correct: 2128
  val_total: 7841
  val_loss: 1.319
  test_accuracy: 22.15%
  test_correct: 1737
  test_total: 7841
  test_loss: 1.3314
  model_file: D:\Neurog_Internship\cryptosight\ml\artifacts\models\BTC_15m_random_forest.joblib
  prediction_file: D:\Neurog_Internship\cryptosight\ml\csv_files\classification\model_predicted\BTC_random_forest_predicted.csv
