dataset_summary:
  exchange: binance
  symbols:
  - BTC
  timeframe: 1m
  target_timeframe: 15m
  start_date: '2025-01-01'
  end_date: '2026-06-30'
  total_rows: 52271
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
features_summary:
  ohlcv: enabled
  features_list:
  - open
  - high
  - low
  - close
  - volume
  - ind_EMA_20
  - ind_EMA_50
  - ind_RSI_14
  - ind_MACD_12_26_9
  - ind_MACD_SIGNAL_12_26_9
  - ind_MACD_HIST_12_26_9
  - pat_DOJI
  - pat_BULLISH_ENGULFING
  indicators:
  - name: EMA
    parameters:
      timeperiod: 20
  - name: EMA
    parameters:
      timeperiod: 50
  - name: RSI
    parameters:
      timeperiod: 14
  - name: MACD
    parameters:
      fastperiod: 12
      slowperiod: 26
      signalperiod: 9
  patterns:
  - DOJI
  - BULLISH_ENGULFING
splits_summary:
  train:
    rows: 36589
    start_timestamp: '2025-01-01 12:30:00+00:00'
    end_timestamp: '2026-01-17 15:30:00+00:00'
  validation:
    rows: 7841
    start_timestamp: '2026-01-17 15:45:00+00:00'
    end_timestamp: '2026-04-09 07:45:00+00:00'
  test:
    rows: 7841
    start_timestamp: '2026-04-09 08:00:00+00:00'
    end_timestamp: '2026-06-30 00:00:00+00:00'
