symbol: BTC
timeframe: 15m
task_type: classification
period:
  start: '2026-04-09 08:00:00'
  end: '2026-06-30 00:00:00'
models:
  xgboost:
    total_rows: 7841
    correct: 2833
    accuracy: 36.13%
    precision: 38.38%
    recall: 39.00%
    signal_distribution:
      buy  (+1):
        actual: 852
        predicted: 3879
      hold (0):
        actual: 6061
        predicted: 2402
      sell (-1):
        actual: 928
        predicted: 1560
  random_forest:
    total_rows: 7841
    correct: 1737
    accuracy: 22.15%
    precision: 42.32%
    recall: 36.66%
    signal_distribution:
      buy  (+1):
        actual: 852
        predicted: 6653
      hold (0):
        actual: 6061
        predicted: 1022
      sell (-1):
        actual: 928
        predicted: 166
  lightgbm:
    total_rows: 7841
    correct: 2624
    accuracy: 33.47%
    precision: 39.18%
    recall: 39.62%
    signal_distribution:
      buy  (+1):
        actual: 852
        predicted: 4702
      hold (0):
        actual: 6061
        predicted: 2086
      sell (-1):
        actual: 928
        predicted: 1053
